name = "TimeWarp"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TimeWarp"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "TimeWarp"
